#!/usr/bin/env bash
# A Bash script that displays a list of all running processes in a user-friendly, hierarchical format

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,cmd --forest
